use UNIVER;

SELECT ISNULL(TEACHER.TEACHER_NAME, '***') [TEACHER], SUBJECT_T.SUBJECT_NAME [SUBJECT]
FROM TEACHER INNER JOIN PULPIT
ON TEACHER.PULPIT = PULPIT.PULPIT
FULL OUTER JOIN SUBJECT_T
ON PULPIT.PULPIT = SUBJECT_T.PULPIT
where TEACHER.TEACHER_NAME IS NULL;

SELECT ISNULL(SUBJECT_T.SUBJECT_NAME, '***') [SUBJECT], TEACHER.TEACHER_NAME [TEACHER]
FROM PULPIT INNER JOIN TEACHER
ON TEACHER.PULPIT = PULPIT.PULPIT
FULL OUTER JOIN SUBJECT_T
ON PULPIT.PULPIT = SUBJECT_T.PULPIT
where SUBJECT_T.SUBJECT_NAME IS NULL;

SELECT SUBJECT_T.SUBJECT_NAME [SUBJECT], TEACHER.TEACHER_NAME [TEACHER]
FROM PULPIT INNER JOIN TEACHER
ON TEACHER.PULPIT = PULPIT.PULPIT
FULL OUTER JOIN SUBJECT_T
ON PULPIT.PULPIT = SUBJECT_T.PULPIT
where SUBJECT_T.SUBJECT_NAME IS NOT NULL AND TEACHER.TEACHER_NAME IS NOT NULL;