use UNIVER;

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
from AUDITORIUM INNER JOIN AUDITORIUM_TYPE
on AUDITORIUM.[AUDITORIUM_TYPE] = AUDITORIUM_TYPE.AUDITORIUM_TYPE
	AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%компьютер%';