use UNIVER;

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
from AUDITORIUM, AUDITORIUM_TYPE
WHERE AUDITORIUM.[AUDITORIUM_TYPE] = AUDITORIUM_TYPE.AUDITORIUM_TYPE;

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
from AUDITORIUM, AUDITORIUM_TYPE
WHERE AUDITORIUM.[AUDITORIUM_TYPE] = AUDITORIUM_TYPE.AUDITORIUM_TYPE
	AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%компьютер%';