use UNIVER;

SELECT PULPIT.PULPIT_NAME [Кафедра],  ISNULL(TEACHER.TEACHER_NAME, '***') [Преподаватель]
FROM TEACHER LEFT OUTER JOIN PULPIT
ON TEACHER.PULPIT = PULPIT.PULPIT;

SELECT PULPIT.PULPIT_NAME [Кафедра],  ISNULL(TEACHER.TEACHER_NAME, '***') [Преподаватель]
FROM PULPIT RIGHT OUTER JOIN TEACHER
ON TEACHER.PULPIT = PULPIT.PULPIT;