use UNIVER;

-- #1
GO
CREATE VIEW [TEACHER_V]
	AS SELECT
		TEACHER.TEACHER_NAME,
		TEACHER.GENDER,
		TEACHER.PULPIT
	FROM TEACHER;

-- #2
use UNIVER;
GO
CREATE VIEW [PULPIT COUNT]
	AS SELECT
		FACULTY.FACULTY_NAME,
		COUNT(PULPIT.FACULTY) [COUNT]
	FROM FACULTY
	JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
	GROUP BY PULPIT.FACULTY, FACULTY.FACULTY_NAME;

-- #3
use UNIVER;
GO
CREATE VIEW [AUDITORIUMS]
	AS SELECT
		AUDITORIUM.AUDITORIUM,
		AUDITORIUM.AUDITORIUM_TYPE
	FROM AUDITORIUM;

GO
INSERT AUDITORIUMS VALUES('315-4', 'À - ');

-- #4
use UNIVER;
GO
CREATE VIEW [LECTURE_AUDITORIUMS]
	AS SELECT
		AUDITORIUM.AUDITORIUM,
		AUDITORIUM.AUDITORIUM_TYPE
	FROM AUDITORIUM
	WHERE AUDITORIUM.AUDITORIUM_TYPE LIKE 'À %' WITH CHECK OPTION;

GO
INSERT LECTURE_AUDITORIUMS VALUES('315-4', 'À - ');

GO
UPDATE [LECTURE_AUDITORIUMS]
SET AUDITORIUM = '415-4'
WHERE AUDITORIUM = '315-4';

-- #5
use UNIVER;
GO
CREATE VIEW [SUBJECTS]
	AS SELECT TOP(10) *
	FROM SUBJECT_T
	ORDER BY SUBJECT_T.SUBJECT_NAME;

-- #6
use UNIVER;
GO
ALTER VIEW [PULPIT COUNT] WITH SCHEMABINDING
	AS SELECT
		FACULTY_NAME,
		COUNT(PULPIT) [COUNT]
	FROM dbo.FACULTY
	JOIN dbo.PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
	GROUP BY FACULTY_NAME;