use UNIVER;

-- №1
SELECT PULPIT.PULPIT_NAME
FROM FACULTY, PULPIT
WHERE FACULTY.FACULTY = PULPIT.FACULTY AND
	FACULTY.FACULTY IN (
		SELECT PROFESSION.FACULTY
		FROM PROFESSION
		WHERE (
			PROFESSION.PROFESSION_NAME LIKE '%технология%' OR
			PROFESSION.PROFESSION_NAME LIKE '%технологии%'
		)
	);

-- №2
SELECT PULPIT.PULPIT_NAME
FROM FACULTY JOIN PULPIT
ON FACULTY.FACULTY = PULPIT.FACULTY AND
	FACULTY.FACULTY IN (
		SELECT PROFESSION.FACULTY
		FROM PROFESSION
		WHERE (
			PROFESSION.PROFESSION_NAME LIKE '%технология%' OR
			PROFESSION.PROFESSION_NAME LIKE '%технологии%'
		)
	);

-- №3
SELECT DISTINCT PULPIT.PULPIT_NAME
FROM FACULTY
JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
JOIN PROFESSION ON PROFESSION.FACULTY = FACULTY.FACULTY AND
	(PROFESSION.PROFESSION_NAME LIKE '%технология%' OR
			PROFESSION.PROFESSION_NAME LIKE '%технологии%');

-- №4
SELECT a.AUDITORIUM,
	a.AUDITORIUM_CAPACITY,
	a.AUDITORIUM_TYPE
FROM AUDITORIUM AS a
WHERE a.AUDITORIUM = (
		SELECT TOP(1) b.AUDITORIUM
		FROM AUDITORIUM AS b
		WHERE b.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE
		ORDER BY b.AUDITORIUM_CAPACITY DESC
	)
ORDER BY a.AUDITORIUM_CAPACITY DESC;

-- №5
SELECT FACULTY.FACULTY_NAME
FROM FACULTY
WHERE EXISTS (
	SELECT * FROM PULPIT
	WHERE PULPIT.FACULTY = FACULTY.FACULTY
);

-- №6
SELECT TOP(1)
	ISNULL((
		SELECT AVG(PROGRESS.NOTE) FROM PROGRESS
		WHERE PROGRESS.SUBJECT_T = 'ОАиП'
	), 0) [ОАиП],
	ISNULL((
		SELECT AVG(PROGRESS.NOTE) FROM PROGRESS
		WHERE PROGRESS.SUBJECT_T = 'БД'
	), 0) [БД],
	ISNULL((
		SELECT AVG(PROGRESS.NOTE) FROM PROGRESS
		WHERE PROGRESS.SUBJECT_T = 'СУБД'
	), 0) [СУБД]
FROM PROGRESS;

-- №7
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_CAPACITY
FROM AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM_CAPACITY >= ALL (
	SELECT AUDITORIUM.AUDITORIUM_CAPACITY
	FROM AUDITORIUM
	WHERE AUDITORIUM.AUDITORIUM_TYPE = 'ЛБ-К'
) AND AUDITORIUM.AUDITORIUM_TYPE = 'ЛБ-К';

-- №8
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_CAPACITY
FROM AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM_CAPACITY < ANY (
	SELECT AUDITORIUM.AUDITORIUM_CAPACITY
	FROM AUDITORIUM
	WHERE AUDITORIUM.AUDITORIUM_TYPE = 'ЛБ-К'
) AND AUDITORIUM.AUDITORIUM_TYPE = 'ЛБ-К';